### ISSUE TITLE
Does not seem to install in Ghidra 10.1.5

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [leommxj/ghidra_csky#2]
I downloaded the latest public beta of Ghidra, which is version 10.1.5

Downloaded the zip file from the Releases

Tried selecting the zip file and I get this message

![image](https://user-images.githubusercontent.com/6146984/183400210-65438a51-f8fe-4a1b-9816-9a4fe6ba65b7.png)

**Comment by leommxj** [comment]
@rogerclarkmelbourne 
try [v0.1.1](https://github.com/leommxj/ghidra_csky/releases/tag/v0.1.1)
ghidra check version string in `extension.properties`, and seems need to be the exact same version :(

**Comment by rogerclarkmelbourne** [comment]
OK. I may try unziping and changing the extension.properties file then re-zipping

**Comment by leommxj** [comment]
@rogerclarkmelbourne 
this release [v0.1.1](https://github.com/leommxj/ghidra_csky/releases/tag/v0.1.1) is built with 10.1.5 and should work with Ghidra 10.1.5.

**Comment by rogerclarkmelbourne** [comment]
I unzipped change the extension.properties to 10.1.5 and re-zipped and Ghidra then accepted the file

I've tried to load firmware file, for a custom chip, which supposedly has  a CSKY core, and Ghidra has found some functions, but probably only 50% or less of the file seems to be decoded by Ghidra.

Unfortunatly I don't know what version of CSKY core is used in this custom chip, so I doubt it will currently be possible to examine the firmware

**Comment by leommxj** [comment]
Hi, @rogerclarkmelbourne 
Maybe try objdump in the official toolchain from https://github.com/c-sky/buildroot/releases to check if it is the ISA you think it is. I think both v3 and v2 toolchains can be found. This processor module indeed missing many instructions as described in Instructions.md, but it normally should do better than 50%.

**Comment by rogerclarkmelbourne** [comment]
OK. I'll do that when I have some free time, but I know very little about the custom chip I was interested in, except some speculation it used a CSKY core.

I have a firmware binary for this custom chip, and it appears to be unencrypted because there are readable strings in it

But its possible it doesn't use the same core as the standalone CSKY processors, as its more of a MCU + extra custom hardware than  CPU
