### ISSUE TITLE
Problem with push and pop while emulating

### ISSUE THREAD

**Issue by deniska-iriska** [leommxj/ghidra_csky#3]
I was using Ghidra as an emulator and came across an oddity. 
The following code (cuted from the real code)
```sh
mov r4, 1
mov r15, 2
push {r4}, r15
pop {r4}, r15
```
will cause the registers `r4` & `r15` to have the following values
```
r4 = 2
r15 = 1
```

Looks like mistake is ['not right order'](https://github.com/leommxj/ghidra_csky/blob/master/CSKY/data/languages/16b_memory.sinc#L74-L75) - the same error for pop32

**Comment by leommxj** [comment]
Thank you for raising the issue. There is indeed a mistake in the handling of the `pop` and `push` instructions.
After some simple test, i think the main problem is in `push` . It should push the register with bigger number first. 
eg. `push r4, r5, r15` will push r15 first, then r5, then r4.
As for the `pop` instruction, it should using the poped r15 register as the next pc.

**Comment by leommxj** [comment]
4e831ddba8730c2ec9c09ce413561420283f6342
